use crate::constants::*;

/// Returns `true` if the character belongs to any defined Tamil Unicode block.
///
/// This covers:
/// - The **Tamil block** (`U+0B80..=U+0BFF`): Independent vowels, consonants, combining vowel signs,
///   virama (pulli), digits (௧–௯, ௦), numerals (௰, ௱, ௲), and symbols (௳–௺, ௐ).
/// - The **Tamil Supplement block** (`U+11FC0..=U+11FFF`): Historical Tamil fractions and symbols.
///
/// # Examples
///
/// ```
/// # use suvadi_core::is_tamil_char;
/// assert!(is_tamil_char('த'));
/// assert!(is_tamil_char('ி'));
/// assert!(is_tamil_char('௰')); // Tamil numeral 10
/// assert!(!is_tamil_char('A'));
/// assert!(!is_tamil_char(' '));
/// ```
#[inline]
pub const fn is_tamil_char(c: char) -> bool {
    matches!(
        c,
        // Standard Tamil block (letters, signs, digits 0-9, symbols 10, 100, 1000)
        '\u{0B80}'..='\u{0BFF}'
        // Optional: Tamil Supplement block (historical fractions & symbols)
        | '\u{11FC0}'..='\u{11FFF}'
    )
}

pub fn has_tamil(word: &str) -> bool {
    word.chars().any(is_tamil_char)
}

/// Returns `true` if `c` is one of the 12 core Tamil combining signs used in grapheme clustering.
///
/// Matches:
/// - Virama / Pulli (`்` - `U+0BCD`)
/// - Dependent vowel signs: `ா`, `ி`, `ீ`, `ு`, `ூ`, `ெ`, `ே`, `ை`, `ொ`, `ோ`, `ௌ`
///
/// *(Note: For complete Unicode coverage including the Au Length Mark `ௗ`, see [`is_tamil_combining_sign`].)*
///
/// # Examples
///
/// ```
/// # use suvadi_core::is_combining_mark;
/// assert!(is_combining_mark('்')); // Pulli
/// assert!(is_combining_mark('ா')); // Aa sign
/// assert!(!is_combining_mark('க')); // Base consonant
/// ```
pub const fn is_combining_mark(c: char) -> bool {
    matches!(c, '்' | 'ா'..='ூ' | 'ெ'..='ை' | 'ொ'..='ௌ')
}

/// Returns `true` if `c` is an independent Tamil vowel (*உயிர் எழுத்து* - Uyir Ezhuthu).
///
/// Matches the 12 independent primary vowels:
/// `அ`, `ஆ`, `இ`, `ஈ`, `உ`, `ஊ`, `எ`, `ஏ`, `ஐ`, `ஒ`, `ஓ`, `ஔ`.
///
/// Does **not** match dependent vowel signs (உயிர்மெய் குறிகள்) or the Ayudham (`ஃ`).
///
/// # Examples
///
/// ```
/// # use suvadi_core::is_uyir;
/// assert!(is_uyir('அ'));
/// assert!(is_uyir('ஔ'));
/// assert!(!is_uyir('ா')); // Dependent sign, not independent vowel
/// assert!(!is_uyir('க')); // Consonant
/// assert!(!is_uyir('ஃ')); // Ayudham
/// ```
pub const fn is_uyir(c: char) -> bool {
    matches!(
        c,
        VOWEL_A
            | VOWEL_AA
            | VOWEL_I
            | VOWEL_II
            | VOWEL_U
            | VOWEL_UU
            | VOWEL_E
            | VOWEL_EE
            | VOWEL_AI
            | VOWEL_O
            | VOWEL_OO
            | VOWEL_AU
    )
}

/// Returns `true` if `c` is any Tamil combining sign, including the Au Length Mark.
///
/// Matches:
/// - Pulli / Virama (`்` - `U+0BCD`)
/// - Primary dependent vowel signs (`ா`..=`ூ`, `ெ`..=`ை`, `ொ`..=`ௌ`)
/// - Tamil Au Length Mark (`ௗ` - `U+0BD7`), frequently generated by Tamil IMEs for diphthong decomposition
///
/// # Examples
///
/// ```
/// # use suvadi_core::is_tamil_combining_sign;
/// assert!(is_tamil_combining_sign('்'));
/// assert!(is_tamil_combining_sign('ௗ'));
/// assert!(!is_tamil_combining_sign('அ'));
/// ```
#[inline(always)]
pub const fn is_tamil_combining_sign(c: char) -> bool {
    matches!(
        c,
        '்' | 'ா' | 'ி' | 'ீ' | 'ு' | 'ூ' | 'ெ' | 'ே' | 'ை' | 'ொ' | 'ோ' | 'ௌ' | 'ௗ'
    )
}

/// Tokenizes a string into a list of Tamil letters (*எழுத்துக்கள்*) and individual non-Tamil characters.
///
/// Unlike standard [`str::chars`], which splits multi-byte Unicode code points and severs
/// combining vowel signs and pulli from their base consonants, this function preserves whole
/// Tamil grapheme clusters:
/// - Pure consonants with pulli (*மெய்*: e.g., `க்`, `ழ்`)
/// - Consonant-vowel compounds (*உயிர்மெய்*: e.g., `கா`, `மி`, `போ`)
/// - Independent vowels (*உயிர்*: e.g., `அ`, `ஐ`)
///
/// Non-Tamil characters (Latin letters, whitespace, punctuation, digits) are emitted as
/// single-character tokens.
///
/// # Examples
///
/// ```
/// # use suvadi_core::get_letters;
/// assert_eq!(
///     get_letters("தமிழ்"),
///     vec!["த", "மி", "ழ்"]
/// );
///
/// assert_eq!(
///     get_letters("Rust மொழி"),
///     vec!["R", "u", "s", "t", " ", "மொ", "ழி"]
/// );
/// ```
pub fn get_letters(x: &str) -> Vec<String> {
    if x.is_empty() {
        return Vec::new();
    }

    let mut v = Vec::with_capacity(x.len() / 3 + 1);

    let mut char_indices = x.char_indices();
    let (mut start, first_c) = match char_indices.next() {
        Some(pair) => pair,
        None => return v,
    };
    let mut end = start + first_c.len_utf8();

    for (idx, c) in char_indices {
        if is_combining_mark(c) {
            end = idx + c.len_utf8();
        } else {
            v.push(x[start..end].to_string());
            start = idx;
            end = idx + c.len_utf8();
        }
    }

    v.push(x[start..end].to_string());
    v
}

/// Tokenizes the string into isolated Tamil orthographic letters, discarding
/// all non-Tamil characters (ASCII, Latin script, Arabic numerals, whitespace, and punctuation).
///
/// This performs zero-copy grapheme segmentation via [`get_letter_slices`], retaining
/// only tokens containing valid characters from the Unicode Tamil block (`U+0B80..=U+0BFF`)
/// and the Tamil Supplement (`U+11FC0..=U+11FFF`).
///
/// # Examples
///
/// ### 1. Siddhar Philosophical Axiom (*Tirumandiram 2104*)
/// Demonstrates stripping whitespace and punctuation from classical Siddhar literature
/// ("One humanity, one divine origin"):
/// ```
/// # use suvadi_core::get_tamil_letters_only;
/// assert_eq!(
///     get_tamil_letters_only("ஒன்றே குலம் (One Humanity)"),
///     vec!["ஒ", "ன்", "றே", "கு", "ல", "ம்"]
/// );
/// ```
///
/// ### 2. Classical Sangam Murugan Epithet (*Paripāṭal / Tolkāppiyam*)
/// Tests complex consonant clusters and doubled virama (*meyyeḻuttu*) ligatures
/// using the ancient indigenous title for Murugan (*Sevvēḷ* — "The Luminous Spear-Bearer"):
/// ```
/// # use suvadi_core::get_tamil_letters_only;
/// assert_eq!(
///     get_tamil_letters_only("செவ்வேள்: குறிஞ்சி-தலைவன்"),
///     vec!["செ", "வ்", "வே", "ள்", "கு", "றி", "ஞ்", "சி", "த", "லை", "வ", "ன்"]
/// );
/// ```
///
/// ### 3. Siddhar Epistemology & Pure Consonants
/// Tests consecutive stop consonants (*ப்*, *பொ*) in *Meipporuḷ* ("Ultimate Truth / Essence"):
/// ```
/// # use suvadi_core::get_tamil_letters_only;
/// assert_eq!(
///     get_tamil_letters_only("மெய்ப்பொருள் #108"),
///     vec!["மெ", "ய்", "ப்", "பொ", "ரு", "ள்"]
/// );
/// ```
///
/// ### 4. Non-Tamil Input
/// Returns an empty vector when no Tamil code points exist:
/// ```
/// # use suvadi_core::get_tamil_letters_only;
/// assert_eq!(
///     get_tamil_letters_only("Murugan Sevvel 2026"),
///     Vec::<String>::new()
/// );
/// ```
pub fn get_tamil_letters_only(x: &str) -> Vec<String> {
    get_letters(x)
        .into_iter()
        .filter(|token| token.chars().any(is_tamil_char))
        .map(String::from)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_combining_signs_return_true() {
        let combining_signs = [
            '்',  // Virama / Pulli
            'ா',  // Aa sign
            'ி', // I sign
            'ீ',  // Ii sign
            'ு', // U sign
            'ூ', // Uu sign
            'ெ', // E sign
            'ே', // Ee sign
            'ை', // Ai sign
            'ொ', // O sign
            'ோ', // Oo sign
            'ௌ', // Au sign
        ];

        for &sign in &combining_signs {
            assert!(
                is_tamil_combining_sign(sign),
                "Expected '{}' (\\u{{{:04X}}}) to be recognized as combining sign",
                sign,
                sign as u32
            );
        }
    }

    #[test]
    fn test_non_combining_characters_return_false() {
        let non_combining = [
            // Independent vowels (உயிர் எழுத்துக்கள்)
            'அ', 'ஆ', 'இ', 'ஈ', 'உ', 'ஊ', 'எ', 'ஏ', 'ஐ', 'ஒ', 'ஓ', 'ஔ',
            // Base consonants (மெய் எழுத்துக்கள் without pulli)
            'க', 'ங', 'ச', 'ஞ', 'ட', 'ண', 'த', 'ந', 'ப', 'ம', 'ய', 'ர', 'ல', 'வ', 'ழ', 'ள', 'ற',
            'ன', // Ayudham
            'ஃ', // ASCII / English letters and digits
            'a', 'Z', '0', '9', ' ', '!',
        ];

        for &c in &non_combining {
            assert!(
                !is_tamil_combining_sign(c),
                "Expected '{}' (\\u{{{:04X}}}) NOT to be recognized as combining sign",
                c,
                c as u32
            );
        }
    }

    #[test]
    fn test_empty_string() {
        let result = get_letters("");
        assert!(result.is_empty());
    }

    #[test]
    fn test_pure_vowels() {
        // Words made entirely of independent vowels
        let input = "அம்மா"; // 'அ', 'ம்' ('ம' + '்'), 'மா' ('ம' + 'ா')
        let expected = vec!["அ", "ம்", "மா"];
        assert_eq!(get_letters(input), expected);
    }

    #[test]
    fn test_standard_tamil_words() {
        // "தமிழ்" -> த (U+0BA4), மி (U+0BAE + U+0BBF), ழ் (U+0BB4 + U+0BCD)
        assert_eq!(get_letters("தமிழ்"), vec!["த", "மி", "ழ்"]);

        // "வணக்கம்" -> வ, ண, க், க, ம்
        assert_eq!(get_letters("வணக்கம்"), vec!["வ", "ண", "க்", "க", "ம்"]);

        // "முருகன்" -> மு, ரு, க, ன்
        assert_eq!(get_letters("முருகன்"), vec!["மு", "ரு", "க", "ன்"]);
    }

    #[test]
    fn test_all_vowel_sign_combinations() {
        let input = "க கா கி கீ கு கூ கெ கே கை கொ கோ கௌ க்";
        let letters = get_letters(input);
        let expected = vec![
            "க", " ", "கா", " ", "கி", " ", "கீ", " ", "கு", " ", "கூ", " ", "கெ", " ", "கே", " ",
            "கை", " ", "கொ", " ", "கோ", " ", "கௌ", " ", "க்",
        ];
        assert_eq!(letters, expected);
    }
    #[test]
    fn test_mixed_tamil_and_english() {
        let input = "Rust மொழி";
        let expected = vec!["R", "u", "s", "t", " ", "மொ", "ழி"];
        assert_eq!(get_letters(input), expected);
    }

    #[test]
    fn test_ayudha_letter() {
        // 'ஃ' is an independent letter and should not attach to previous letters
        let input = "அஃது";
        let expected = vec!["அ", "ஃ", "து"];
        assert_eq!(get_letters(input), expected);
    }

    #[test]
    fn test_edge_case_leading_combining_sign() {
        // Malformed input starting with a combining sign should not panic
        let input = "்அ";
        let expected = vec!["்", "அ"];
        assert_eq!(get_letters(input), expected);
    }

    #[test]
    fn test_edge_case_isolated_combining_signs() {
        let input = "்ா";
        let expected = vec!["்ா"];
        assert_eq!(get_letters(input), expected);
    }

    #[test]
    fn test_murugan_saravanabhava_pure_tamil() {
        let input = "ௐ சரவணபவ போற்றி (Om Saravanabhava Potri)";
        let expected = vec![
            "ௐ", // Tamil Pranava / Om (U+0BD0)
            "ச", "ர", "வ", "ண", "ப", "வ", // சரவணபவ
            "போ", "ற்", "றி", // போற்றி (Pure Tamil for Namah)
        ];
        assert_eq!(get_tamil_letters_only(input), expected);
    }

    #[test]
    fn test_purananuru_cosmopolitan_motto() {
        let input = "யாதும் ஊரே யாவரும் கேளிர் - கணியன் பூங்குன்றனார் (Universal Brotherhood)";
        let expected = vec![
            "யா", "து", "ம்", // யாதும்
            "ஊ", "ரே", // ஊரே
            "யா", "வ", "ரு", "ம்", // யாவரும்
            "கே", "ளி", "ர்", // கேளிர்
            "க", "ணி", "ய", "ன்", // கணியன்
            "பூ", "ங்", "கு", "ன்", "ற", "னா", "ர்", // பூங்குன்றனார்
        ];
        assert_eq!(get_tamil_letters_only(input), expected);
    }
}
